### ISSUE TITLE
Update based on commit message

### ISSUE THREAD

**Issue by bilogic** [MichaelCurrin/auto-tag#12]
I was wondering... how about this?

1. If there is a semver tag in the latest commit, exit
2. If latest commit containts `[MAJOR]`, increment major, exit
3. If latest commit containts `[MINOR]`, increment minor, exit
4. Increment patch, exit

**Comment by MichaelCurrin** [comment]
That is very different logic to what autotag does based on user input.

I made a Gist with two scripts you can choose from, thanks to ChatGPT :)

I did some light testing and it looks it makes sense

See if this works for you

https://gist.github.com/MichaelCurrin/83373c6dae8c6f8d147b5b3cc82fdc7b

**Comment by bilogic** [comment]
hey thanks so much! I was concerned I wasn't going to get a reply here, so I did up a PHP version today, but much prefer the bash since it can work instantly anywhere, however, I'm not proficient in bash. Let me check it out in a bit!

**Comment by bilogic** [comment]
Having used this autotagging algo since Feb, I must say it works great to the extend that versioning no longer requires any attention from me. :)
